import './about.css'

export const metadata = {
    title: 'About Page',
    description: 'Generated by app router',
}

export default function AboutLayout({ children }) {
    return (
        <html lang="en">
            <body >
                {children}</body>
        </html>
    )
}
