import AuthProvider from '@/context/AuthContext'
import './globals.css'
import ThemeProvider from '@/context/ThemeContext'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <AuthProvider>
            {children}
          </AuthProvider>
        </ThemeProvider>

      </body>
    </html>
  )
}
